// examples/polotno-vue/src/App.vue
<template>
  <Observer>
    <div class="header">
      <div>
        This header is controlled by Vue. It can be used to display the number
        of pages: {{ store.pages.length }}
      </div>
      <button @click="store.addPage">Add page</button>
    </div>
    <div id="editor"></div>
  </Observer>
</template>

<script setup>
import * as ReactDOM from 'react-dom/client';
import * as React from 'react';
import { App, store } from './components/editor';
import { Observer } from 'mobx-vue-lite';

import { onMounted, onUnmounted } from 'vue';

let root;
onMounted(() => {
  root = ReactDOM.createRoot(document.getElementById('editor'));
  root.render(React.createElement(App));
});

onUnmounted(() => {
  root?.unmount();
});
</script>

<style>
body {
  margin: 0;
  padding: 0;
}

.header {
  height: 10vh;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
</style>

// examples/polotno-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import * as ReactDOM from "react-dom/client";
import * as React from "react";
import { App, store } from "./polotno/editor";
import { MobxAngularModule } from 'mobx-angular';


// inside the module you have access to "store" object.
//You can use any of its API to control the canvas from angular app
// for more methods take a look here:   https://polotno.com/docs/store-overview
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  standalone: true,
  imports: [MobxAngularModule],
})
export class AppComponent {
  title = "polotno-js";
  root: ReactDOM.Root | undefined;
  store = store;
  ngOnInit(): void {}

  public ngOnChanges() {
    this.renderComponent();
  }

  public ngAfterViewInit() {
    this.root = ReactDOM.createRoot(document.getElementById("root"));
    this.renderComponent();
  }

  private renderComponent() {
    this.root.render(React.createElement(App));
  }

  public ngOnDestroy() {
    if (this.root) {
      this.root.unmount();
    }
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div>
  <div *mobxAutorun class="header">
    <div>
      This header is controlled by Angular. It can be used to display the number
      of pages: {{ store.pages.length }}
    </div>
    <div>
      <button (click)="store.addPage()">Add Page</button>
    </div>
  </div>
  <div id="root"></div>
</div>
